language: csharp
dist: trusty

matrix:
  include:
    - mono: 5.8.0
      env: USE_DOTNET_CLI=1
      os: linux
    - mono: latest
      env: USE_DOTNET_CLI=1
      os: osx
    - mono: 5.12.0
      env: USE_MSBUILD=1
      os: linux
    - mono: latest
      env: USE_MSBUILD=1
      os: osx
    - mono: latest
      env: USE_MSBUILD=1
      os: linux
      
sudo: true  # use the new container-based Travis infrastructure

script:
  - ./build.sh Pack

allow_failures:
    - mono: weekly
      env: USE_MSBUILD=1
      os: linux
